---
include:
  - path: ../backend/docker-compose.yml

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: area-frontend
    ports:
      - "${FRONTEND_PORT:-8081}:80"
    depends_on:
      - backend
    networks:
      - area-network

networks:
  area-network:
    name: area-network
