---
include:
  - path: ../backend/docker-compose.yml

services:
  frontend:
    build:
      context: ..
      dockerfile: client_web/Dockerfile
      args:
        - VITE_DEPLOY_ADDRESS=${VITE_DEPLOY_ADDRESS:-localhost}
    container_name: area-frontend
    environment:
      - VITE_DEPLOY_ADDRESS=${VITE_DEPLOY_ADDRESS:-localhost}
    ports:
      - "${FRONTEND_PORT:-8081}:80"
    depends_on:
      - backend
    networks:
      - area-network

networks:
  area-network:
    name: area-network
