---
include:
  - path: ../backend/docker-compose.yml

services:
  frontend:
    build:
      context: ..
      dockerfile: client_web/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-localhost}
    container_name: area-frontend
    environment:
      - VITE_DEPLOY_ADDRESS=${VITE_DEPLOY_ADDRESS:-localhost}
    ports:
      - "${FRONTEND_PORT:-8081}:8081"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    depends_on:
      - backend
    networks:
      - area-network

networks:
  area-network:
    name: area-network
