---
include:
  - path: ../database/docker-compose.yml
  - path: ../redis/docker-compose.yml
  - path: ../vault/docker-compose.yml

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: area-backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST:-haproxy}
      - POSTGRES_PORT=${POSTGRES_PORT:-5000}
      - POSTGRES_NAME=${POSTGRES_NAME:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BACKEND_PORT=${BACKEND_PORT:-8080}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_HOST=${REDIS_HOST:-area-cache}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - VAULT_ADDR=http://vault:8200
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      patroni1:
        condition: service_healthy
      patroni2:
        condition: service_healthy
      patroni3:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      cache:
        condition: service_started
      vault:
        condition: service_started
    networks:
      - area-network
      - patroni

  migration:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: area-migration
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST:-haproxy}
      - POSTGRES_PORT=${POSTGRES_PORT:-5000}
      - POSTGRES_NAME=${POSTGRES_NAME:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    command: pnpm db:push
    depends_on:
      patroni1:
        condition: service_healthy
      patroni2:
        condition: service_healthy
      patroni3:
        condition: service_healthy
    networks:
      - area-network
      - patroni

networks:
  area-network:
    name: area-network
  patroni:
    name: area-patroni

volumes:
  postgres_data:
